### ISSUE TITLE
Minor inconsistency in Dynamo.Sequences

### ISSUE THREAD

**Issue by strongeye** [ServiceStack/ServiceStack.Aws#6]
Dynamo.Sequences.Increment<T>(...) returns a long for next sequence
while 
Dynamo.Sequences.Reset<T>(...) accepts an int

**Comment by mythz** [comment]
Yep, it was because it was expected Reset to use a low number like 0 :) 

But I've updated `ISequenceSource` to use longs in these commits:

 - https://github.com/ServiceStack/ServiceStack/commit/4de12a2f3f46de2ffefb935c2a81be97e8075d05
 - https://github.com/ServiceStack/ServiceStack.Aws/commit/67e0271bd95fecf844ffdeb615191ce68d81c574
